### ISSUE TITLE
Is there a docker image from DockerHub for us to pull and use the Poplar SDK environment?

### ISSUE THREAD

**Issue by ghostplant** [graphcore/popart#1]
Is there a docker image from DockerHub for us to pull and use the Poplar SDK environment?

**Comment by LRVerkin** [comment]
I'm happy to let you know that starting from today, Graphcore is a verified publisher on DockerHub and so the Graphcore Docker images can be downloaded from DockerHub.

You can find them here: https://hub.docker.com/u/graphcore
