### ISSUE TITLE
https://github.com/jessicawleigh/popart/issues/8#issue-1520770123

### ISSUE THREAD

**Issue by Elhamkr** [graphcore/popart#5]

**Comment by Elhamkr** [comment]
https://github.com/jessicawleigh/popart/issues/8#issue-1520770123

**Comment by ManueleSigona** [comment]
We're going to close this issue as well, for the reasons explained in the comment here: https://github.com/graphcore/popart/issues/7#issuecomment-1373451683.

Manuele,
Graphcore
